language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - composer install --no-interaction --prefer-source
    - php app/console doctrine:database:create --env=test
    - php app/console doctrine:schema:update --force --env=test

script: phpunit -c app
