<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260226090859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'initial migration';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pairing (id UUID NOT NULL, source_url TEXT NOT NULL, selected_destination_id UUID DEFAULT NULL, plan_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8816ECFCB10B97CE ON pairing (selected_destination_id)');
        $this->addSql('CREATE INDEX IDX_8816ECFCE899029B ON pairing (plan_id)');
        $this->addSql('CREATE TABLE pairing_destination (id UUID NOT NULL, destination_url TEXT NOT NULL, pairing_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FBEE4D59DC8046BD ON pairing_destination (pairing_id)');
        $this->addSql('CREATE TABLE plan (id UUID NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE pairing ADD CONSTRAINT FK_8816ECFCB10B97CE FOREIGN KEY (selected_destination_id) REFERENCES pairing_destination (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pairing ADD CONSTRAINT FK_8816ECFCE899029B FOREIGN KEY (plan_id) REFERENCES plan (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pairing_destination ADD CONSTRAINT FK_FBEE4D59DC8046BD FOREIGN KEY (pairing_id) REFERENCES pairing (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pairing DROP CONSTRAINT FK_8816ECFCB10B97CE');
        $this->addSql('ALTER TABLE pairing DROP CONSTRAINT FK_8816ECFCE899029B');
        $this->addSql('ALTER TABLE pairing_destination DROP CONSTRAINT FK_FBEE4D59DC8046BD');
        $this->addSql('DROP TABLE pairing');
        $this->addSql('DROP TABLE pairing_destination');
        $this->addSql('DROP TABLE plan');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
